[[pipeline.txt]]
cmd = "cp"
arguments = ["$infile", "$outfile"]
new_extension = "md"

[[pipeline.weird_css]]
cmd = "cp"
arguments = ["$infile", "$outfile"]
new_extension = "weird_css"

[[pipeline.tailwind]]
cmd = "cp"
arguments = ["$infile", "$outfile"]
new_extension = "tailwind"

[pipelines]
extension_map = { css = "weird_css" }
special_files = { "tailwind.css" = "tailwind" }

[[pipelines.pre_build]]
cmd = "touch"
arguments = ["$distdir/pre_build_ran"]

[[pipelines.post_build]]
cmd = "touch"
arguments = ["$distdir/post_build_ran"]
