[[resources.scss]]
type = "run.command"
command = "scss_css_transpiler"
output = "stdout" # default : "file" | valid values: "file" | "stdout" | "stderr"
arguments = "-O3 --file=$input" # $input gets replaced with the input file. To get a literal dollar sign, use `$$`, e.g. `"$$input=meow"` adds an argument matching "$input=meow"

[[resources.scss]]
type = "css.minify"

[[resources.ts]]
type = "run.command"
command = "typescript"
output = "file"
# default: ""
argument = "-O3 --input=$input --output=$output" # when the output is set to `file`, another variable called `$output` is added.

[[resources.ts]]
type = "js.minify"

[[resources.png]]
type = "webp.from_png"
result = "webp"

[[resources.png]]
type = "run.pipeline"
pipeline = "resources.webp"

[[resources.webp]]
type = "change_filename"
expression = "'img_$filename'"

[default_keys]
name = "wiru"
email = "dev.willians.faria@gmail.com"
homepage = "https://wiru.st/"

[config]
output = "dist/"
index = "index.md" # default: "index.html"
err_page = "_404.html" # default: "_404.html"
