[[pipelines.prebuild]]
cmd = "touch"
arguments = ["$rootdir/test1.txt"]

[[pipelines.postbuild]]
cmd = "touch"
arguments = ["$rootdir/test1.txt"]

[[pipeline.txt]]
cmd = "cp"
arguments = ["$infile", "$outfile"]
new_extension = "md"
